name: ci

on:
  push:
    tags: ["v*"]
    branches: [ main ]

  pull_request:
    branches: [ main ]

env:
  dn: ghcr.io/${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install pre-commit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo wget https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 -O /usr/bin/hadolint
        sudo chmod +x /usr/bin/hadolint

    - name: Code checks
      run: export SKIP=no-commit-to-branch; pre-commit run --all

  deploy:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
      run: |
        tag_name="${GITHUB_REF#refs/tags/}"
        set -eux
        docker build . --file Dockerfile --tag ${dn}:${tag_name}
        docker tag ${dn}:${tag_name} ${dn}:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}

    - name: Publish the Docker image
      run: |
        tag_name="${GITHUB_REF#refs/tags/}"
        set -eux
        docker push ${dn}:${tag_name}
        docker push ${dn}:latest

  compile:

    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
    needs: ["build"]
    strategy:
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python x64 on ubuntu
      if: ${{ contains(matrix.os, 'ubuntu') }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Set up Python x86 on windows
      if: ${{ contains(matrix.os, 'windows') }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        architecture: x86

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: building executable
      run: pyinstaller --onefile svrusoundbot.py

    - name: building a static executable file
      # if: ${{ startsWith(matrix.os, 'ubuntu') }}
      if: ${{ false }} # skeep 
      # See https://github.com/JonathonReinhart/staticx/issues/188
      run: |
        set -eux
        python -m pip install staticx
        staticx --strip dist/svrusoundbot dist/svrusoundbot-static
        strip -s -R .comment -R .gnu.version --strip-unneeded dist/svrusoundbot-static
        mkdir -p dist/tmp
        rm dist/svrusoundbot
        mv dist/svrusoundbot-static dist/svrusoundbot

    - uses: actions/upload-artifact@v3
      with:
        name: exe_for_${{ matrix.os }}
        path: dist/svrusoundbot*

  uploadrelease:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
    needs: ["build", "compile"]
    steps:
    - uses: actions/checkout@v3
    - name: download releases files
      uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: exe_for_*/svrusoundbot*
        fail_on_unmatched_files: true
        append_body: true
